### ISSUE TITLE
Failed to load positions: Column positions.realized_pnl_sat does not exist

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1006]
```
Failed to sync closed DLCs with positions in database: Failed to load open and closing positions: column positions.realized_pnl_sat does not exist

Failed to get positions. Error: DatabaseError(Unknown, "column positions.realized_pnl_sat does not exist")
````

**Comment by bonomat** [comment]
Was this thrown in the app or in the coordinator?

**Comment by bonomat** [comment]
> Was this thrown in the app or in the coordinator?

Answering my own question: it's happening on the coordinator on our testnet VM

**Comment by bonomat** [comment]
I believe this is bug which won't appear in production: 

the problem stems from @da-kami having added the migration for 
https://github.com/get10101/10101/blob/e46a2be0c55a7c31ebeb8ca0826f5d9c96d5738c/coordinator/migrations/2023-07-19-055143_closed_positions/up.sql#L7

in this commit 7c7bed7b4e3a4354e7d6d564bc4a59d8e2543a10 which used `realized_pnl`

`realized_pnl_sat` was only introduced in e46a2be0c55a7c31ebeb8ca0826f5d9c96d5738c. 

I assume we deployed the first patch on regtest before the latter one and hence the migration was not run again. 

Because of this we currently have an invalid state in the db

```
id | contract_symbol | leverage | quantity | direction | average_entry_price | liquidation_price | position_state | collateral |      creation_timestamp       |    expiry_timestamp    |       update_timestamp        |                           trader_pubkey                            |                      temporary_contract_id                       | realized_pnl | unrealized_pnl_sat | closing_price
```

**Comment by bonomat** [comment]
Fixed by removing the db and restarting the coordinator: the migration has been run again. 

New table has the correct fields:

```
 id | contract_symbol | leverage | quantity | direction | average_entry_price | liquidation_price | position_state | collateral | creation_timestamp | expiry_timestamp | update_timestamp | trader_pubkey | temporary_contract_id | realized_pnl_sat | unrealized_pnl_sat | closing_price

(0 rows)
```
