### ISSUE TITLE
Recover app on-chain wallet from seed

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1079]
Implement a way to create a new 10101 app based on an existing 10101 seed.

For example, after a fresh install we confront the user with the choice to either create a new wallet or to import an existing seed.

Caveat: this only affects the on-chain wallet for now. To recover the channels we need to [back up more data](https://github.com/get10101/10101/issues/1098) and allow the user to import this data on a fresh install.

**Comment by luckysori** [comment]
We should also seriously consider backing up the `rust-dlc` and `rust-lightning` data needed to reconstruct the node remembering all the keys needed to recover funds that are not yet owned by the on-chain wallet. This would make it much safer for people to have to reinstall their app.

**Comment by luckysori** [comment]
I put it back into `New` so that we can pay attention to this next time we plan an iteration.

@holzeis and I had a chat about this yesterday and we agreed that **the fact that our seed phrase is non-standard** is something worth addressing soon.

We currently use BIP39 to generate a mnemonic phrase, but instead of using it directly we hash it in two different ways to derive one seed for the on-chain wallet and another for LDK's `KeysManager`. The advantage of this is that we only have to back up one seed for two purposes. In practice this is not actually useful because (1) we have not yet implemented a way to recover a 10101 wallet using this seed and, more importantly, (2) you would not be able to recover the whole 10101 wallet just with this seed[^1].

The main disadvantage of the current approach is that a user cannot use their mnemonic phrase to recover their on-chain funds using a different wallet. If they do want to recover their on-chain funds they would need to use something like https://github.com/get10101/bip39-to-bip32/ to learn the BIP32 key of their on-chain wallet. Then they could import it into a tool such as Sparrow. This whole process is unnecessarily complicated.

I would propose to simply generate one BIP39 seed for the on-chain wallet and a separate seed for LDK and to **only expose the on-chain seed to the user in the `Back up your wallet` screen**. The LDK seed is not useful on its own AFAIK and we should probably back it up with the rest of the LDK data[^1].

[^1]: https://github.com/get10101/10101/issues/1098.

**Comment by luckysori** [comment]
@luckysori to split up this ticket.
