### ISSUE TITLE
Add cargo tests to ci pipeline

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#113]
With https://github.com/get10101/10101/pull/105 we introduced two important tests for single and multi hop payments. These, and other cargo tests should get executed automatically on the pipeline according to the [ci strategy](https://github.com/get10101/10101/blob/main/docs/001-ci-strategy.adoc).

Note, the tests are currently dependent on a filesystem lock, due to the wallet using the sled db. Thus the tests can not be executed in parallel as otherwise the single and multi hop payment tests will compete over the database lock (and one test will always fail) The only workaround at the moment is to run the tests in a single thread.

```
cargo test -- --test-threads=1
```

**Comment by bonomat** [comment]
> Note, the tests are currently dependent on a filesystem lock, due to the wallet using the sled db. 

A simple solution here would be to use different folders.

**Comment by bonomat** [comment]
I've fixed this issue in: [`489b1c6` (#105)](https://github.com/get10101/10101/pull/105/commits/489b1c6e5f5f5d5507f00dffaee7dedbb329150b)

**Comment by bonomat** [comment]
Note that the tests introduced in #105 need a blockchain setup. I'm not sure we want these to run on CI, at least not regularly but only when corresponding files have been changed.

**Comment by bonomat** [comment]
An issue I see with our current tests in #105 is that they [depend on nigiri](https://github.com/get10101/10101/blob/4d79b1025a00a5d881b2e182df251795166e0496/crates/ln-dlc-node/src/tests/mod.rs#L98-L116) which we can't (easily) install on CI. I tried it on my fork for a quick test and it fails due to some filesystem permission errors. 

https://github.com/bonomat/10101/actions/runs/4130258472/jobs/7136761470
