### ISSUE TITLE
Flaky test `maker_can_open_channel_to_coordinator_and_send_payment`

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1244]
CI repro [here](https://github.com/get10101/10101/actions/runs/6105399183/job/16568856595#step:14:2058).

**Comment by klochowicz** [comment]
is it actually that test? 
looking at the CI output, the previous test has run into some issues with the state of the lightning channel:

`2023-09-07T04:40:00.154503Z ERROR dlc_manager::sub_channel_manager: Got close notification from LDK in a state that we don't handle yet    `

probably that's why the subsequent test couldn't pay the invoice.

🤔 we might need to add a sanity check for the LN and DLC states at the beginning and end of tests to catch these errors better!

**Comment by bonomat** [comment]
@klochowicz : this should not have an impact on the test @luckysori mentioned as in this test we are opening the channel from the maker using on-chain funds.

**Comment by bonomat** [comment]
The issue in this test seems to be esplora: the maker was not able to broadcast the fund transaction and the channel was force-closed immediately. 

One assumption I have is that the maker might have been funded using a coinbase tx and it was not able to spend the money yet. I'll give it a try here: https://github.com/get10101/10101/pull/1252

**Comment by bonomat** [comment]
> One assumption I have is that the maker might have been funded using a coinbase tx and it was not able to spend the money yet. I'll give it a try here: #1252

Note: this was not the case. This ticket is still up for grabs.

**Comment by bonomat** [comment]
Parked until this happens again.
