### ISSUE TITLE
Allow user to close an existing channel so that they can open a new one

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1282]

**Comment by klochowicz** [comment]
the users can close a channel, but I guess it would be good to prompt them to do so, because it's not obvious at all.

something like a dialog when the user wants to add more funds, like
>  "you're trying to add more funds? great news! We've recently added a feature that allows bigger channels! In order to do so, you need to first close the current channel from the Settings screen"

or something like that.

Or, in the simplest case, an email or in-app message / push notification that says the same.

**Comment by bonomat** [comment]
This is done, the flow will be reworked in #1471
