### ISSUE TITLE
Live refresh on-chain transactions

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1288]
Currently, the on-chain transactions are only refreshed at app startup. They should be refreshed continuously as with lightning payments.

**Comment by Restioson** [comment]
Looks like we just need to sync the wallet

**Comment by luckysori** [comment]
Hey, @Restioson. I think this issue is not correct. The app uses the `ln_dlc_node::Node`, which when `start`ed syncs the on-chain wallet periodically in the background:

https://github.com/get10101/10101/blob/0b30115a8350c93336d9e90dcf1864d9d40d6a3c/crates/ln-dlc-node/src/node/mod.rs#L435-L438

I'm gonna close this issue given what I indicated above.

**Comment by Restioson** [comment]
Oops, my bad 😅 maybe the interval was just too long for me to notice

**Comment by luckysori** [comment]
> Oops, my bad 😅 maybe the interval was just too long for me to notice

Very likely as it's set to 5 minutes by default:

https://github.com/get10101/10101/blob/0b30115a8350c93336d9e90dcf1864d9d40d6a3c/crates/ln-dlc-node/src/node/mod.rs#L203

I do think 5 minutes is okay (and perhaps we shouldn't even sync periodically in a mobile app?) since the on-chain sync is also triggered by:

- Restarting the app.
- Pulling down on the wallet screen.
