### ISSUE TITLE
Can't trade against regtest coordinator

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1330]
Trying to take an order fails at the moment with the following error on the coordinator side: 

```
Sep 19 18:43:14 get10101-testnet coordinator[1409002]: {"timestamp":"2023-09-19T18:43:14.472976645Z","level":"ERROR","fields":{"error":"InvalidOrder(\"trader_id=03ed85b37d020d88e25c9307ce68341caa2d41b3991554b5cec8a2380a7096f1cf, order_id=c00f58ff-5f2c-45ff-a6d9-da3c2c97688e, Order is currently in execution. Can't accept new orders until the order execution is finished\")"},"target":"coordinator::orderbook::routes","span":{"name":"post_order"},"spans":[{"name":"post_order"}]}
```

- 03ed85b37d020d88e25c9307ce68341caa2d41b3991554b5cec8a2380a7096f1cf
- 2125
- 1.2.6

**Comment by holzeis** [comment]
@bonomat You had multiple open orders and a single order in state `Matched`. The `Matched` order prevented you from submitting yet another order. It's a safeguard.

Do you remember what you've done to end up in that state?

### Open Orders
I am wondering how you managed to have orders in state `Open` as our api either sets them to `Matched` or `Failed` but it should always end up in either state. Maybe the coordinator restarted exactly at that time, but you had too many instances as that could be a logical explanation.

- [ ] Regardless on how you managed to end up with an open order. We should set them to `Failed` if they have been expired.

### Matched Order
You might have closed the app immediately after your order was submitted, preventing the app from immediately executing the trade by calling the trade api?

- [ ] That could be fixed by executing also our regular trades as async trades, e.g. informing the user upon a new start of the app that a pending match is still waiting for her. That would have fixed your issue. (I guess)
- [ ] I guess what we should also do is to add a timeout handling for matched orders that never get executed. At the moment we are executing it immediately with the maker and are optimistic about the taker. At some timeout, we should give up on the taker and counter trade with the maker again.

**Comment by bonomat** [comment]
This was potentially fixed by @holzeis
