### ISSUE TITLE
Coordinator panicked

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1338]
Regtest environment

Coordinator cannot be re/started because it panics: 

```
{"timestamp":"2023-09-20T18:34:31.339767813Z","level":"ERROR","fields":{"message":"Aborting after panic in task","info":"panicked at 'not implemented', /home/tentenone/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/962265b/dlc-manager/src/manager.rs:1918:9"},"target":"coordinator"}
```

**Comment by klochowicz** [comment]
I suspect this was a side effect of  #1327 , which might have required a DB wipe after merging.

I've added a quickfix that logs an error instead of bringing down the whole app when it notices an expired sub-channel and asked Tibo before I jump head-first into the issue itself.

Will keep this ticket updated.

**Comment by holzeis** [comment]
> I suspect this was a side effect of https://github.com/get10101/10101/pull/1327 , which might have required a DB wipe after merging.

I doubt that this change had anything to do with it, maybe we are running into this issue because we are now using the `RenewOffer` when rolling over introduced with https://github.com/get10101/10101/pull/1287.
