### ISSUE TITLE
We should not expect that the url for the orderbook is a domain

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1391]
Right now we expect the url for the orderbook in the maker is a domain, but it could very much be a single IP address: 
https://github.com/get10101/10101/blob/edae35ca34599e49174c4ff37856fccb6c13a63b/maker/src/orderbook_ws.rs#L48

It's not a "real" bug but I'm declaring it as such because we didn't know and it panicked in production.

**Comment by holzeis** [comment]
There is a real bug as well because if you use the default port 80 the maker panics in this line 

https://github.com/get10101/10101/blob/edae35ca34599e49174c4ff37856fccb6c13a63b/maker/src/orderbook_ws.rs#L49

I had to expose the 8000 port additionally to 81 so that I was able to configure the maker properly, without a panic on parsing the port.

It appears if you provide the endpoint like that `http://api.10101.finance:80` that the port `80` gets ignored and parsing it fails. We must not expect there, but simply assume the default for the protocol (80 for http and 443 for https)
