### ISSUE TITLE
Investigate diesel

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#142]
For our databases (e.g. #26 ) we want to consider [Diesel](https://diesel.rs/) instead sqlx this time. 

The goal of this ticket is to have a simple PoC setup with CRUD functionality

Things to look into: 
- can we have a swappable DB, e.g. can we switch postgres for sqlite? 
- how complex does the model get compared to sqlx?
- any other obvious drawbacks?

**Comment by 1010Tom** [comment]
I've started with this today. 
In case someone wants to have a look (cc @da-kami ) how to use diesel in a simple setup, please checkout this branch: 
https://github.com/get10101/10101/compare/feat/orderbook?expand=1

Regarding the outlined questions

> can we have a swappable DB, e.g. can we switch postgres for sqlite?

Short answer: it is not easily possible to write generic code which would allow us to use either sqlite or postgres. 

Longer answer: https://github.com/diesel-rs/diesel/issues/2384


> how complex does the model get compared to sqlx?

So far I can't say much about this due to using very simple types.

> any other obvious drawbacks?

It's sync but that shouldn't be a problem (imho)

**Comment by da-kami** [comment]
Note: Have you considered using [`diesel-async`](https://github.com/weiznich/diesel_async)? 
At least for Posres it supports a full async connection. It's created by the creator of diesel.
(Very long discussion here: https://github.com/diesel-rs/diesel/issues/399)

Not saying that we will *need* it from the getgo, but with sync code we will limit the number of db connections that can execute to the number of threads (and a threadpool). I think for the app and sqlite that should be fine, I don't expect heavy load there, but for the Ordinator this might be a different story, as there will be more load.

We can roll with a sync implementation initially and can see :)

**Comment by 1010Tom** [comment]
> Note: Have you considered using [`diesel-async`](https://github.com/weiznich/diesel_async)?

I don't see the need for async yet. I would assume that our db queries are super short running which should hopeflly hardly have an effect on the remaining application.

**Comment by bonomat** [comment]
We decided to go with diesel for mobile #26  and the coordinator #27
