### ISSUE TITLE
History tab in trade

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#147]
We moved the `trades` into the `order` because it simplifies the UI. However, there are other events happening around your `position` which are not related to an `order` anymore, e.g. `rollovers/fees`. 

We should add a `history` tab  which depicts the `trades` as well as `position`-related actions such as `rollover` and `trading fees`.

**Comment by da-kami** [comment]
@bonomat I had some more thoughts on this and came up with a slightly different solution: 

We could just depict the "trade history" in the wallet history. We already have planned to depict filled orders there (because funds are being moved from the wallet to "trading"). We would also depict closing the position in the wallet history, because the funds transition from being locked up in the DLC back into the wallet. 
The wallet history item could contain the information about the historical position then.

---

Here's some more context:

- The orders reflects how the position was altered *by the user* over time.
- Additionally, there automated "rollovers" alter the position over time: Fees, (unrealized) profit/loss

As long as a position is open we can display rollover information on the position details.

When a position gets closed (by an order with the counter direction and same quantity as currently open position) then the rollover information *should* still be available to the user somewhere (in addition to the order history).

- Profits/Loss of the position 
- fees that incurred over time (this is mainly for transparency reasons; we could also decide to just dump this information for now)
 
We could just distinguish this in the wallet history as well; because in the end the funds move back into the wallet:

- Order that opens/changes a position -> Always moves funds from the wallet to trading position
- Order that closes a position -> Moves funds from trading position to the wallet; this entry could contain the information about the position.

**Comment by luckysori** [comment]
What should we do with this ticket? @bonomat @da-kami

**Comment by bonomat** [comment]
Not highest priority but something relatively easy to add.
