### ISSUE TITLE
App is crashing at startup since upgrade to 1.6.0

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1661]
The app is crashing for some of our users after upgrading to 1.6.0.

```
[E] TIME: 2023-11-24T18:42:12.320227Z Launching the app failed FfiException(RESULT_ERROR, Failed to start the backend

Caused by:
    0: Failed to initialise DlcManager
    1: Storage error Unknown required feature preventing decode, null)
```

**Comment by luckysori** [comment]
It might be helpful to see more logs from the user.

The user reported that they were able to open up the app on version `1.5.0`. Unclear whether they were able to do it on `1.6.0` or not, their messages were ambiguous.

The error above is associated with being unable to load the `ChainMonitor` when constructing the `dlc_manager::Manager` (aka the `DlcManager`).

We introduced breaking changes to the `ChainMonitor` with version `1.5.0`, but we also added some code before building the `DlcManager` to ensure backwards-compatibility:

```rust
// FIXME: We need to do this to ensure that we can upgrade `Node`s from LDK 0.0.114 to 0.0.116.
// We should remove this workaround as soon as possible.
if let Err(e) = dlc_storage.get_chain_monitor() {
    tracing::error!("Failed to load DLC ChainMonitor from storage: {e:#}");

    tracing::info!("Overwriting old DLC ChainMonitor with empty one to be able to proceed");
    dlc_storage.persist_chain_monitor(&dlc_manager::chain_monitor::ChainMonitor::new(0))?;
}
```

In theory, any time we fail to load the `ChainMonitor` because of a breaking change, we should print these logs and overwrite the `ChainMonitor` with an empty one. This is not a long term fix, but we thought it was acceptable for now, since we weren't even loading the persisted `ChainMonitor` before these changes due to a [bug in `rust-dlc`](https://github.com/p2pderivatives/rust-dlc/pull/166).

I don't really see how we could be failing on startup given all this, since the code pasted above is still present in `>=1.6.0` and our `rust-dlc` and `rust-lightning` dependencies haven't been updated since then.

A theory could be that our relatively new implementation of `DlcStorageProvider` is not working correctly because:

1. we are not loading the `ChainMonitor` from the same spot where we persist it; or
2. when we call `persist_chain_monitor` we are not actually overwriting the existing `ChainMonitor`.

Full logs would be helpful here.

**Comment by luckysori** [comment]
>     1. we are not loading the `ChainMonitor` from the same spot where we persist it; or

We have a test for this, so this is covered.
 
>     2. when we call `persist_chain_monitor` we are not actually overwriting the existing `ChainMonitor`.

Looking into this.
