### ISSUE TITLE
Can't load order screen:  bad state

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1669]
Just happened in production: closed a position and wanted to trade again. 
Saw the error below: 

![image](https://github.com/get10101/10101/assets/224613/b0c7e600-da3f-4043-a95b-e269eb751ab6)

Uploading the logs on the phone is failing ... will do it later on my laptop

**Comment by bonomat** [comment]
this was on iOS 1.6.6

**Comment by holzeis** [comment]
> this was on iOS 1.6.6 in production 

Is it reproducible? 

My guess is that you may have updated to 1.6.6 before the coordinator was updated. When you opened the app again it did not reconnect to the websocket and thus did not send another authenticate message so that you did not receive the initial LSP config data, which is now returned in the authenticated response instead of fetched from the the http api.

**Comment by bonomat** [comment]
It hasn't happened again ever since. Closing this for now and will re-open if it does.
