### ISSUE TITLE
Add `Send Max` button in sending on-chain screen

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1925]

**Comment by Restioson** [comment]
Just to confirm - are we wanting to replace the '0 to send max' with a button as in the figma?

![Image](https://github.com/get10101/10101/assets/6688948/e2ecd54b-3927-49be-9d70-8ce4c641cea1)

**Comment by Restioson** [comment]
I wonder what clicking it should do to the amount field :thinking: it could set it to show the balance, and set the actual amount to just drain. But, if you changed it and then re-typed it (e.g if bal = 20389 and you typed 20389 manually) it would say that the amount is too large, since there are fees to be paid too. Whereas, with draining, it's implied you're sending as much as possible after fees

**Comment by bonomat** [comment]
See my comment here: https://github.com/get10101/10101/pull/1931#issuecomment-1918691238
