### ISSUE TITLE
Retry backup if backup failed

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2117]
At the moment we simply ignore a backup that failed, which can very likely result into a broken app after using that backup when restoring.

We should be more resilient towards the backup failing and keep a list of failed backup attempts and regularly try them again.

**Comment by luckysori** [comment]
Radical idea: what if we drop support for backups? Now that users don't have Lightning channels[^1], it's not too bad to just recover the on-chain wallet using the seed phrase and wait for the corresponding CET or settle transaction to be published.

It's obviously not ideal as you have to trust that 10101 will eventually close your channel (and that they won't publish an old transaction!), but recovering from a seed will always be a small edge case.

I think the backup feature is cool (when it works), but I'm skeptical that it is worth maintaining at this stage, particularly since we are not using Lightning anymore.

[^1]: It wasn't so simple with Lightning, because the commitment transaction outputs usually had to be claimed by some key via LDK.
