### ISSUE TITLE
Be able to close position

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#220]
When the trader is `100 long` and goes `100 short` the position should be closed. 

The idea is that when the trader post `api/trade` the coordinator does the math and then tells the trader to close the DLC collaboratively. 

For this ticket to work we will need to implement things on the coordinator and the app at the same time.

Related to #181

**Comment by holzeis** [comment]
I started to look into this ticket. Here are my two cents.


### Closing a Position on the mobile app

Closing a position basically means creating a "reversed" order of the position which is currently open. e.g. if the existing position is long then the order will be short.

This will mean we will be able to close a Position two ways through the UI. Either you hit the `Close Position` button on the Position itself, or you open a Short Order through the trade screen. 

In any case we have to ensure (for the MVP) that if e.g. a long position exists the short order can only get submitted with the same quantity as the long position (as we will not support partial closing of a position for MVP).

### Closing a Position on the coordinator

After the order is submitted to the coordinator, the coordinator looks for existing positions with the submitting counterparty. If a position is found matching the quantity and a "reversed" direction, the coordinator simply proposes to close the dlc_channel with the trader. 

_Note, I don't see the benefit of instructing the mobile app to initiate the closing of the dlc channel, but happy to be convinced otherwise._


### MVP Scope

If we do not support closing a position partially, then I guess we will also not support extending a position. That will basically mean, after you have an open position. The only action you can take as a trader is to close the position. Meaning that we can simplify things here in the implementation as we can assume that another order submitted by the trader can only be a request to close the position if a position already exists.

**Comment by bonomat** [comment]
> In any case we have to ensure (for the MVP) that if e.g. a long position exists the short order can only get submitted with the same quantity as the long position (as we will not support partial closing of a position for MVP).

I think this is a fair limitation which we should be able to enforce through the frontend.



> ### Closing a Position on the coordinator
> 
> After the order is submitted to the coordinator, the coordinator looks for existing positions with the submitting counterparty. If a position is found matching the quantity and a "reversed" direction, the coordinator simply proposes to close the dlc_channel with the trader.

I'd like to keep the _normal_ order flow, i.e. 
1. the trader posts a `market order` to the `orderbook`[^1] , 
2. once there is a match, the `orderbook` tells the trader _how_ to trade
3. the trader then goes against the `coordinator`: since the only allowed action is a total close, the trader will end-up with no DLC channel.

Note: @2: for the MVP the only matched order will come from our maker

Note: @3: while the trader's DLC channel will be void afterwards it might be that we need to re-size the channel of the maker. I'm not sure if we want to limit us to have only 1 trade open for the maker as well?

[^1]: Note: I distinguish on purpose between `orderbook` and `coordinator` although they are the same binary so that we keep thinking of them in terms of separate entities.
