### ISSUE TITLE
The max button always leads to a dlc protocol error

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2309]
Environment: test

1. Open a new channel
2. Choose max on the channel configuration.

For me this always ended up in a dlc protocol error. I presume the max does not correctly consider on-chain and order matching fees.

![image](https://github.com/get10101/10101/assets/382048/f4b08dfd-5703-409c-b1fe-366a6a50f5e8)

**Comment by luckysori** [comment]
I wasn't able to reproduce this. Can you provide more context, @holzeis?

**Comment by bonomat** [comment]
I wasn't able to reproduce it neither. 

1. closed existing channel
2. send out all funds but 500k sats
3. opened a channel with max amount. 
success

**Comment by luckysori** [comment]
@holzeis: Philipp and I were able to reproduce it and figure out why this is happening.

1. Create fresh app.
2. Receive _two_ UTXOs. Keep the sum of both UTXOs below the actual maximum determined by the coordinator i.e. 6M sats.
3. Attempt to open a channel with maximum collateral.

Run into the error:

```
2024-03-25T02:22:45.103055619Z ERROR process_dlc_channel_offer{channel_id="70feedddf1f857a2d909906c8251a46eee27e5163615d102de7d840dbdaec424"}: native::ln_dlc::node: Failed to accept dlc channel offer. Wallet error Wallet does not hold enough UTXOs to cover amount 1009559 with fee rate 3. No bnb solution found after 0 rounds (max rounds is 100000).
```

The problem arises because we use an estimate of the funding TX fee based on a transaction with a single input per party. This is okay because the estimate was meant to be used... well, as an estimate for informational purposes.

Now that we are using this value for something more important we need to be a bit more conservative. I propose to simply multiply this value by two to cover our bases. The user will not be missing out on that much collateral.
