### ISSUE TITLE
Add info why leverage can't be changed with an open position

### ISSUE THREAD

**Issue by pythcoiner** [get10101/10101#2450]
![image](https://github.com/get10101/10101/assets/124568858/b21750b8-8ce0-4b2e-8141-b0b33f5c59ac)

On Pixel 7a w/ 2.2.0 10101 app

**Comment by luckysori** [comment]
Hey, @pythcoiner! Thanks for the report.

When you ran into this behaviour, did you already have an open position? If so, not being able to interact with the slider is expected behaviour. At the moment, you cannot change the leverage for a position that is already open. This is a feature that should come in the future.

But if you ran into this _without_ an open position, we'll have to investigate further because that would be a bug.

**Comment by pythcoiner** [comment]
right position already open, i think a short hint over/under slidder should be useful if its intended behaviour
