### ISSUE TITLE
Market orders may get starved if submitted into empty orderbook

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#276]
This is likely just because the orderbook is not complete yet, this particular scenario is a bit annoying though, because when one starts the maker "too late" it's not obvious that an already submitted market order will not be matched against the limit order of the maker.

Scenarios:

- No limit order in orderbook (because e.g. maker was down, ...)
- Trader submits market order -> no match found

The market order is never re-matched. When a limit order is sbumitted it is not matched at the moment.

**Comment by holzeis** [comment]
I guess that's because we only perform the match order when an market order gets posted. In your scenario no match has been found, and any subsequent limit order submission skips the matching logic. 

I guess the proper solution would be to perform the match logic in a task interval and process any market order that has not yet been taken.

**Comment by bonomat** [comment]
> The market order is never re-matched. When a limit order is sbumitted it is not matched at the moment.

Note: this was a design choice for now. We shoul fail the http request if no match was found.
