### ISSUE TITLE
`ChannelMonitor was stored in the wrong file`

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#299]
```
flutter: | 2023-03-21 15:42:23.872 | LogLevel.ERROR | Failed to initialise: Error: ChannelMonitor was stored in the wrong file
```

Once the we run into this the app won't start anymore - will always run into this error. 
I ran into this error after repeatedly starting and stopping the app - there is no clear pattern to reproduce this though, it happend quite randomly. 

Daniel's guess: We don't close *some* database when we exit the app gracefully, so it can happen that a lock is still there or some file gets corrupted.

**Comment by bonomat** [comment]
This happened on the coordinator on our testnet setup as well and only way out was to delete the data directory

**Comment by holzeis** [comment]
Lucas and I looked at this issue and we believe it is caused by the rust-dlc fiddling with the funding transaction. Using the rust-lightning file persister we fail on the following sanity check, which verifies if the name of the file matches the funding transaction within. 

https://github.com/lightningdevkit/rust-lightning/blob/3d479c9de62665214e8589699cdbb8a797b77188/lightning-persister/src/lib.rs#L110-L113

As this goes astray for the dlc enabled channels, the sanity check fails and we can't start the coordinator anymore. A simple quick fix would be to simply disable the sanity check (since we know better :). Eventually we need to replace the file persister anyways with a database persister, so I guess that approach is sensible.

**Comment by holzeis** [comment]
Further investigations revealed that this bug has another symptoms (I suspect depending on the scenario)

**Scenario: Restart with an open position (without any closed dlcs)**

The coordinator can be restarted successfully in this state, however a subsequent close of the open position will result into the following error.

```
2023-03-24 16:03:44 ERROR lightning::chain::chainmonitor: Failed to update channel monitor funding txo: no such monitor registered    
2023-03-24 16:03:44 ERROR coordinator: Unable to process internal message: Invalid parameters were provided: Misuse error: Could not update channel funding transaction.
```
