### ISSUE TITLE
10101 mobile app can reach unfundable state

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#333]
### Repro

1. Fresh install of 10101 app on TestFlight (version 1.0.0, build 46).
2. Generate an invoice to fund the app.
3. _Close the app_.
4. Attempt to pay invoice via public faucet.
5. Payment fails because the app is closed (`no_route`).
6. Open the app and generate a new invoice.
7. Keep the app open.
8. Attempt to pay invoice via public faucet.
9. Payment fails due to `no_route`.

The app never recovers from this. The cause is unknown. The only workaround is to reinstall the app, generating a new seed.

---

A note on step 5: we know that the app has to be open in order to receive payments. Ideally we would leave the HTLC pending until the user opens the app (via a push notification perhaps). For now, we don't need to fix the error in step 5, as the user is only ever funding their app once and we can instruct them to keep it open.

**Comment by luckysori** [comment]
@holzeis and I were able to reproduce this.

**Comment by holzeis** [comment]
This seems to be a lnd issue only. I retested the same scenario with 2 10101 apps and a subsequent payment of the same invoice, after the first one failed due to the app not being open on the other phone, succeeded without any issues. I guess lnd is marking the recipient as unreachable and hence ignores any following attempt.

**Comment by holzeis** [comment]
After some digging I found that lnd is keeping a heuristic for routing attempts based on past payment attempts. This information is kept in the mission control and seems to block any subsequent payment to a node that has previously failed. Since it is the very first payment that fails I guess this heuristic is heavily opinionated.

https://docs.lightning.engineering/lightning-network-tools/lnd/payments#mission-control

Adding the following **step 8** to your scenario will make the payment succeed through the faucet.

1. Fresh install of 10101 app on TestFlight (version 1.0.0, build 46).
2. Generate an invoice to fund the app.
3. Close the app.
4. Attempt to pay invoice via public faucet.
5. Payment fails because the app is closed (no_route).
6. Open the app and generate a new invoice.
7. Keep the app open.
---
8. Clear lnds mission control running `lncli --no-macaroons --network regtest resetmc`
---
9. Attempt to pay invoice via public faucet.
10. Payment fails due to no_route.

**Comment by luckysori** [comment]
@holzeis:

> 10. Payment fails due to no_route.

I guess you meant to say that the payment _succeeds_ in your previous comment.

**Comment by holzeis** [comment]
> I guess you meant to say that the payment _succeeds_ in your previous comment.

yes, indeed 😅
