### ISSUE TITLE
Cap the channel size

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#383]
- the limit should be shown on the invoice view.
- the max amount of sats that can be received applies whether a channel already exist or not. (As we don't support extending channels yet)
- if a payment is received with an amount exceeding the channel cap, the htlc should transition to failed. (note, this is already the case if a channel already exists)

**Comment by holzeis** [comment]
We could show a similar limit on the send payment screen.

**Comment by da-kami** [comment]
Notes:

- after #397 we already have the `200k` in the `TradeService` but since this value concerns the wallet as well it should be moved into a separate service.
- I would add Form validation to the `Receive` screen to validate the value
- In the trade screen, when the user runs low on capacity we recommend to balance the channel 50/50 - I would probably do the same in the Receive screen for now to keep it simple.
