### ISSUE TITLE
Imply the trade inbound and outbound transactions from the dlc contracts

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#388]
🙃 Given that we use `rust-dlc` to execute the collaborative settlement, we should take the PNL from the `ClosedContract` state.

Something like this would work:

```rust
let contracts = node
    .dlc_manager
    .get_store()
    .get_contracts()
    .unwrap();
let contract = contracts
    .first()
    .unwrap();

let pnl = match contract {
    dlc_manager::contract::Contract::Closed(
        ClosedContract { pnl, .. }
    ) => pnl,
    _ => panic!("Wrong state"),
}
```

~Unfortunately, I've tested it locally and I think there is a bug in the branch of `rust-dlc` we are using. I've reported it [here](https://matrix.to/#/!YOUZSBmuJuaGzmxzaA:matrix.org/$VvoCFBGABMfoY-QgnU1u7NK9kFHXIwE4hOB25Ps3N4o?via=matrix.org)~. Bug has been fixed and we just need to upgrade to latest `rust-dlc`.

_Originally posted by @luckysori in https://github.com/get10101/10101/pull/384#discussion_r1162302445_

**Comment by holzeis** [comment]
@luckysori is this still relevant or can we close that?

**Comment by luckysori** [comment]
Still relevant because we're using the wrong values.

It's harder to fix than anticipated: we have no link between the `ClosedContract` and the closed position at the moment. And the suggested heuristic of taking the `first` contract should not work and is a bit scary.

All in all I'd rather fix it properly by keeping track of the `ContractId` rather than trying to hack this together. I'm closing the issue for now, as the reported values should be close enough.
