### ISSUE TITLE
App cannot receive payment with open position

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#498]
### how to reproduce

1. Fund the wallet 
2. Open position
3. Receive money on the wallet

The transaction is shown in the history but not in the balance.

![image](https://user-images.githubusercontent.com/382048/234048083-fb3931c2-9fe6-48ea-bb9f-d390f3d6a171.png)

**Comment by holzeis** [comment]
Note, I waited long enough to exclude that the wallet has simply not been synchronised.

**Comment by bonomat** [comment]
Can confirm this bug. It happens on my iPhone as well. 
Also after a restart the money does not show up. 

The problem is, you also can't use the funds because the wallet thinks that the money is not there and sending is disabled because of this: 


![image](https://user-images.githubusercontent.com/224613/234051904-4c3f0d87-579c-45ab-9077-bd14e71436d6.png)

**Comment by bonomat** [comment]
We decided to not allow creating invoices while a position is open.

**Comment by klochowicz** [comment]
Removed the 'critical' label in light of our decision to not allow new invoices whilst the position is open.

**Comment by holzeis** [comment]
Just tested this bug on the latest version and it seems it is fixed. 🚀🎉
