### ISSUE TITLE
Non-collaborative closure of the DLC channel

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#51]
Closing the DLC channel without collaboration requires the publication of certain transactions.

We want to verify that:

- [x] #770
- [x] On-chain DLC can be claimed via CET. (#612 proves this).
- [ ] #769
- [x] Claimed DLC funds end up in the right wallets. (#612 proves this).
- [x] The Lightning channel can once again be upgraded to an LN-DLC channel (see [this test](https://github.com/get10101/10101/blob/714c7f7597896bacc390de99586df1dfd7c4d4ed/crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs#L135)).

**Comment by da-kami** [comment]
What happens if the user opens a DLC sub-channel and then closes the Lightning channel?
Is the expected behaviour that the DLC part would be paid out according to the oracle attestation?

---

Would it make sense to "simplify" the ticket to just close the Lightning channel and assert that the money is distributed as expected.

**Comment by luckysori** [comment]
@klochowicz: Should I take this over since you're busy with other stuff? If you have anything locally, could you push it to a branch?

**Comment by klochowicz** [comment]
> @klochowicz: Should I take this over since you're busy with other stuff? If you have anything locally, could you push it to a branch?

that would actually be most helpful; I haven't progressed with this much due to dealing with non-coding tasks 😢

**Comment by luckysori** [comment]
Refund and the finishing touches on force-close are tracked elsewhere now.
