### ISSUE TITLE
Dev setup is only ready after a node anouncement after the channel creation

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#570]
Recently we've changed the interval from every minute to every 10 minutes. That increases the time we have to wait before we can make use of the channel in our development setup.

If we try to fund our wallet before the node announcement we get the following error on the coordinator

```
Failed to accept/forward incoming HTLC: Unable to decode our hop data   
```

And a `no route` error on the faucet.

I propose to on top of the interval that we make a node announcement after the channel ready event (with a small delay).

------

I think its fine for a productive setup, though.

**Comment by klochowicz** [comment]
Removed the MVP badge from this, because the most pressing issue seems to be solved.

**Comment by bonomat** [comment]
I have the assumption that this error is not related to node announcement because we can the channel to send funds from LND to the coordinator. 

This is what we tried: 

1. fund coordinator 
2. mine blocks
3. fund lnd
4. mine blocks
5. open channel
6. mine blocks
7. create invoice on coordinator (`curl -G -d 'amount=12345' -d 'description=test' -d 'expiry=12345' http://localhost:8000/api/invoice`)
8. paste invoice in online faucet

The error above only comes when trying to pay an invoice of the app. 

Maybe @klochowicz can chip in who made it work today. Did you still notice this error?
