### ISSUE TITLE
Add send screen

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#58]
it should be possible to send to an address (manual input) as well as scan a qr code

**Comment by da-kami** [comment]
Flow for sending a payment:

![2023-01-31 15 06 58](https://user-images.githubusercontent.com/5557790/215661399-9fc5e18b-4f31-452d-bd50-7fc06ec9e0a5.gif)

Note: I did https://github.com/get10101/10101/issues/59 as part of this, because `send` is related to the scanner and it made sense to define the flow together. 

We can also keep the scanner screen simpler initially, the buttons there can be removed initially.
