### ISSUE TITLE
Use coordinator for open channel faucet

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#633]
For the faucet, I propose to use the coordinator directly to open a channel with the app instead of using LND. 
This will allow us to remove one source of errors.

I see alot of work putting into the LND settup which is not worth the time at the moment.

**Comment by bonomat** [comment]
Somewhat related to 

- https://github.com/get10101/10101/pull/632
- https://github.com/get10101/10101/issues/610#issuecomment-1542900745
- https://github.com/get10101/10101/pull/631

**Comment by klochowicz** [comment]
there's not much there's not much work happening for this specific reason, I think the most important is the fact that our coordinator loses connection to a valid LDK node that's definitely online - which *should not* happen, and IMHO is a critical bug in itself and should be dealt with asap, otherwise we can't really roll out mainnet at all? 
. The fact that we actually can reproduce this behaviour is a good sign, instead of chasing elusive situations.

**Comment by bonomat** [comment]
It's good that this problem is reproducible though and should be handled but for on-boarding users on regtest with fake money we should not need to deal with LND.
