### ISSUE TITLE
Wallet history item details

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#66]
When clicking on a transaction in the wallet the user wants to see some details . 

We can have atleast 3 different transactions in the wallet: 
- lightning transactions
- on-chain transactions
- trading related activities

**Comment by da-kami** [comment]
It would be great if we can achieve a similar look and feel throughout all the list items - and have similar behavior for them when e.g. clicking on them. 

I propose three steps of information:

1. The list tile shows the most important information
2. When taping on the list tile, the tile [expands](https://pub.dev/packages/expandable) (downwards) to show additional information
3. (optional) we show a button `More details` when expanded that would jump to a child-screen with even more information.

For reference, the `PositionListItem` already has an `ExpandablePanel`, see https://github.com/get10101/10101/blob/main/mobile/lib/features/trade/position_list_item.dart

---

Look of the `OrderListItem`:

![image](https://user-images.githubusercontent.com/5557790/221098610-5524b108-84ba-415f-a88d-83a730c64850.png)

Ticket that tracks adding order information in `ExpandablePanel`: https://github.com/get10101/10101/issues/163

**Comment by da-kami** [comment]
As stated in https://github.com/get10101/10101/issues/67#issuecomment-1442828486 I propose to have three levels of information:

1. The list tile (most important information)
2. The expanded list tile (some more information in expansion + link to jump to "more information"); this can be either a separate detail screen or jumping off to a different screen.
3. (optional) Separate detail screen that one can navigate to from buttons in the expansion.

The following designs are not complete, but should give an idea of how I imagine this:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/5557790/221104331-3d5b15c3-beac-4650-9e34-853dc2e654a9.png">

Previously we did not talk about `Position` in the wallet histroy, but just had `Order Filled` entries, but I think that is not great because we cannot easily distinguish between in- and outgoing flow. I think this reflecting the position is more useful for the user (but this might be subjective).

notes on the data (model):

- For the lightning related items it is important to have a fee-breakdown in the expansion
- For the trade items in the wallet history ...
    - ... there are three items:
        1. `Position Opened`: This item is created when there was no position before; funds flow *out* of the wallet
             - this item being the latest trade related item in the wallet histroy indicates that there must be an *open position*
        2. `Position Changed` This item is create when there was a position already and we changed it; funds flow *out* of the wallet
            - this item being the latest trade related item in the wallet histroy indicates that there must be an *open position*
        3. `Position Closed`: This item is created when there was a position, but the position was closed; funds flow *into* the wallet
            - this item being the latest trade related item in the wallet histroy indicates that there *is no position* (the position was closed)
    - ... we add links to jump off to order or position in the expansion

notes on Navigation (for the MVP, this can be optimized later):

- User clicks on `♐︎ Position` Button: Navigate to `Trade` screen with the `Positions` tab being shown.
- User clicks on `♐︎ Order` Button: Navigate to `Trade` screen with the `Orders` tab being shown.
   - We can *eventually* extend this by highlighting the order that we jumped off from
   - We could also add a detail screen that one can reach from *either* jumping off from the wallet *or* jumping off from the `Order` tab in trade. But I would not do that for now.

**Comment by da-kami** [comment]
Note on MVP scope vs the future:

For the MVP what is designed above should be good enough. Once we add partial filling it will become a bit more complicated because closing a position might not be related to exactly 1 order. 

The way I see to solve this is to group things in a smarter way; both in the wallet history and in trade tab.
With partial filling the position tile in the trade tab will also have to reflect the position being reduced first and then just *eventually* being closed.

I would not invest more brainpower into this for the MVP :)

**Comment by da-kami** [comment]
Update including #101 - this is simplified for now, there is only a `Pending` and a `Done` state.

Note: We can opt for including e.g. transaction confirmation information into the details, but that is a nice to have on top given that we have the link to the blockexplorer in there already for transactions.

![image](https://user-images.githubusercontent.com/5557790/223330048-25ded95d-9a80-44bb-9dbc-6c475a7894d0.png)

**Comment by da-kami** [comment]
Closing this ticket because the Figma work is done; the results of above comments is relevant for the implementation in #67
