### ISSUE TITLE
Change `direction` in `position` table to reflect the `coordinator`'s position

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#941]
Right now the field `direction` in the table `position` reflects the position of the trader and not of the coordinator. This should be changed .

**Comment by da-kami** [comment]
I would be careful changing only the direction because it might make it even more confusing.
At the moment the `Position` on the coordinator reflects the trader's position, i.e. all the fields are the trader's (leverage, collateral, ...). If you change only the direction to be the coordinator's then the rest of the fields would still reflect the trader's position.

I would either keep the model as is (potentially making it more clear that the position in the coordinator *is* the trader's position), or change the model to reflect the values of *both* sides (i.e. trader and coordinator).
