### ISSUE TITLE
SQL implementation for `rust-dlc`

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#987]
This should allow us to replace the `dlc-sled-storage-provider` dependency.

**Comment by luckysori** [comment]
@da-kami and I started on this today but after spending some time thinking about what this would entail we are questioning if this is a good idea at this stage because the persisted models are more complex than anticipated. There is so much data being persisted by `rust-dlc` and modeling it using SQL and `diesel` would be a lot of work. Furthermore, maintaining all this would likely be our responsibility as it's hard to justify putting this on Tibo when the alternative is much more convenient to maintain.

Since this was motivated by **allowing users to keep their channels open through updates with breaking changes to these persisted `rust-dlc` models**, we were questioning whether achieving that is worth all this effort, particularly at this stage of the project.

After chatting with Daniel I am leaning towards a no. For me the biggest appeal of completing this ticket would be to be able to apply a simple patch (involving breaking changes to these models) to a buggy open channel, as opposed to having to force-close said buggy channel to upgrade the user to a new version without the bug. Given that 10101 is beta software we could just embrace the fact that force-closing because of bugs is acceptable.

**Comment by bonomat** [comment]
Did we talk to Tibo about his thoughts on replacing `dlc-sled-storage-provide` with an sql one? 

Imho we bought into the maintenance burden already and I believe we will need to invest way more time into this library in the future so I don't think it will make much of a difference. On the contrary, it might even be faster for us not having to context switch between different storage types.

For me the biggest appeal of having sql over sled is:
1. getting rid of file-based storage will allow us to scale better
2. we could use 3rd party services and don't have to run it ourselves (which also take care of backups)
3. for me personally it is easier to reason over a sql database which I could query manually than having a black box sled file which I don't know is inside. 

Eitherway, I understand this does not have the highest priority at the moment but I would like to see to get rid of sled in the long run if possible. 

Happy to close or postpone to the future.

**Comment by da-kami** [comment]
I think in order to come to a more informed decision we should talk to Tibo to understand what big changes might be on the roadmap in the foreseeable future - If we foresee a lot of breaking changes that are hard to migrate we should potentially wait until the library has matured a bit further. 

It would be great if Tibo agrees to maintaining an SQL database, but that would mean more work for him. Currently most breaking changes are just "hidden" by Sled - old data just cannot be loaded, so effectively the library is just not backwards compatible. 

Please note that, given our current code and system structure, I would argue that we need *two* SQL `StorageProvider`s, one for SQLite and one for PostgreSQL. It might be cumbersome maintaining both (for Tibo). I wonder if we can easily achieve to only have one provider impl. As far as I remember it's not easily possible to have DBMS agnostic migration files - we might be able to share the rust model though and add annotations for both DBMS, or control which annotation is used with feature flags.

---

Below is an overview of breaking changes and how hard it is to migrate them - this is from the top of my head and could help us when we approach Tibo to understand where we are and what is to be expected in terms of maintenance investment.

Breaking changes that are easy to migrate:

- Any kind of rename
- Any kind of addition
    - This is time intensive but not difficult (i.e. it is more work than with serializing into Sled)
-  More generally speaking: Any kind of type change in rust, as long as the underlying data representation does not change or can easily be mapped / converted (as part of an sql migration)

Breaking changes that are hard to migrate:

- Removing enum variants: If we map from data in the database to an enum variant, and a variant is removed that can be hard to migrate in some cases, because we just don't know what enum variant to instantiate upon mapping from database data to enum. This might mean that we have to keep (some) old vaiants or have dummy variants that can be used for backwards compatibility.
- Type changes that change the underlying data representation. This may mean that we need in-code migration steps as well, where the data is mapped to the new representation and saved.
     - This is especially difficult for identifier changes (e.g. changing `ContactId` internal from `[u8;32]` to `Uuid`) This would mean that we have to migrate old records to the new identifying representation. This can require updating references across the database... Possible but can be very cumbersome.
- Relationship / Dependency changes in the business logic that have to be reflected in the database.

---

From the first glimpse that @luckysori and me had yesterday I think the current database model would be relatively easy. There is not many relationships to be defined.

**Comment by da-kami** [comment]
After a discussion with @luckysori:

Postponing this ticket does make sense given the current maturity of the library. 
Recommendation is:

- Pay attention to data related changes (i.e. how stable is the underlying data)
- Re-visit this ticket by the end of Q3
- We accept that certain breaking changes will *not* be backwards compatible and upgrading to a new version might require force-closing positions. We can implement a process where we have a time window where users are nudged to collaboratively close a position because of a new version with breaking changes.

**Comment by Restioson** [comment]
Should we move this out of iteration 6 then?

**Comment by bonomat** [comment]
> Should we move this out of iteration 6 then?

It's more here to be `groomed` than to be `done`. :) Let's see if we get some input from @holzeis or @klochowicz

**Comment by holzeis** [comment]
I agree with the maintenance burden. But that will probably mean a bigger change in rust-dlc.

I wouldn't want to do that solely on the 10101 side.

**Comment by bonomat** [comment]
I've removed the `grooming` label for now but let this ticket stay in our backlog.
